# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StockTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.main_title_label = QtWidgets.QLabel(self.main_tab)
        self.main_title_label.setGeometry(QtCore.QRect(350, 230, 71, 41))
        self.main_title_label.setStyleSheet("background-color: rgb(255, 204, 167);")
        self.main_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_title_label.setObjectName("main_title_label")
        self.tabWidget.addTab(self.main_tab, "")
        self.add_tab = QtWidgets.QWidget()
        self.add_tab.setObjectName("add_tab")
        self.tabWidget.addTab(self.add_tab, "")
        self.NasdaqShareOrders_tab = QtWidgets.QWidget()
        self.NasdaqShareOrders_tab.setObjectName("NasdaqShareOrders_tab")
        self.GetNasdaqShareOrdersButton = QtWidgets.QPushButton(self.NasdaqShareOrders_tab)
        self.GetNasdaqShareOrdersButton.setGeometry(QtCore.QRect(310, 230, 101, 17))
        self.GetNasdaqShareOrdersButton.setObjectName("GetNasdaqShareOrdersButton")
        self.tabWidget.addTab(self.NasdaqShareOrders_tab, "")
        self.DailyShortInterest_tab = QtWidgets.QWidget()
        self.DailyShortInterest_tab.setObjectName("DailyShortInterest_tab")
        self.getLatestDailyShortInterestButton = QtWidgets.QPushButton(self.DailyShortInterest_tab)
        self.getLatestDailyShortInterestButton.setGeometry(QtCore.QRect(310, 230, 141, 17))
        self.getLatestDailyShortInterestButton.setObjectName("getLatestDailyShortInterestButton")
        self.tabWidget.addTab(self.DailyShortInterest_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_title_label.setText(_translate("MainWindow", "Stock Tools"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), _translate("MainWindow", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add_tab), _translate("MainWindow", "+"))
        self.GetNasdaqShareOrdersButton.setText(_translate("MainWindow", "Nasadq Share Orders"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NasdaqShareOrders_tab), _translate("MainWindow", "Nasdaq Share Orders"))
        self.getLatestDailyShortInterestButton.setText(_translate("MainWindow", "Get Latest Daily Short Interest"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DailyShortInterest_tab), _translate("MainWindow", "Daily Short Interest"))
